#Generated by duck.ai
#prompt = "minimal working example tkinter radiobutton gridlayout"
import tkinter as tk

def show_selection():
    selected_value = var.get()
    label.config(text=f"Selected: {selected_value}")

# Create the main window
root = tk.Tk()
root.title("Radio Button Example")

# Create a variable to hold the selected value
var = tk.StringVar(value="Option 1")

# Create radio buttons
radio1 = tk.Radiobutton(root, text="Option 1", variable=var, value="Option 1", command=show_selection)
radio2 = tk.Radiobutton(root, text="Option 2", variable=var, value="Option 2", command=show_selection)
radio3 = tk.Radiobutton(root, text="Option 3", variable=var, value="Option 3", command=show_selection)

# Place radio buttons in the grid
radio1.grid(row=0, column=0, padx=10, pady=5)
radio2.grid(row=1, column=0, padx=10, pady=5)
radio3.grid(row=2, column=0, padx=10, pady=5)

# Label to display the selected option
label = tk.Label(root, text="Selected: Option 1")
label.grid(row=3, column=0, padx=10, pady=10)

# Start the main event loop
root.mainloop()
