#Generated by duck.ai
#prompt = "minimal working example tkinter numeric input box like a shopping cart"
import tkinter as tk

def calculate_total():
    try:
        quantity_item1 = int(entry_item1.get())
        quantity_item2 = int(entry_item2.get())
        quantity_item3 = int(entry_item3.get())
        
        total = (quantity_item1 * price_item1) + (quantity_item2 * price_item2) + (quantity_item3 * price_item3)
        label_total.config(text=f"Total: ${total:.2f}")
    except ValueError:
        label_total.config(text="Please enter valid quantities.")

# Prices of items
price_item1 = 10.00  # Price for Item 1
price_item2 = 15.00  # Price for Item 2
price_item3 = 20.00  # Price for Item 3

# Create the main window
root = tk.Tk()
root.title("Shopping Cart")

# Labels for items
label_item1 = tk.Label(root, text="Item 1 ($10.00):")
label_item1.grid(row=0, column=0, padx=10, pady=5)

label_item2 = tk.Label(root, text="Item 2 ($15.00):")
label_item2.grid(row=1, column=0, padx=10, pady=5)

label_item3 = tk.Label(root, text="Item 3 ($20.00):")
label_item3.grid(row=2, column=0, padx=10, pady=5)

# Entry boxes for quantities
entry_item1 = tk.Entry(root)
entry_item1.grid(row=0, column=1, padx=10, pady=5)

entry_item2 = tk.Entry(root)
entry_item2.grid(row=1, column=1, padx=10, pady=5)

entry_item3 = tk.Entry(root)
entry_item3.grid(row=2, column=1, padx=10, pady=5)

# Button to calculate total
button_calculate = tk.Button(root, text="Calculate Total", command=calculate_total)
button_calculate.grid(row=3, column=0, columnspan=2, pady=10)

# Label to display the total
label_total = tk.Label(root, text="Total: $0.00")
label_total.grid(row=4, column=0, columnspan=2, pady=10)

# Start the main event loop
root.mainloop()
